### PR TITLE
feat: add ctrl-a to ctrl-z to key enums

### PR DESCRIPTION
**Pull request by chyroc**
Please open an issue and discuss changes before spending time on them, unless the change is trivial or an issue already exists.

### CODE REVIEW

**Comment by chyroc** [comment]
hi, thanks for you terminal input read repo.

i found some feat need to add to this repo.

i try to check if input is `ctrl + a` , i try to use `e.Ctrl() && e.Rune() == 'a'`, but `e.Ctrl()` is not true, and i fail.

i try to print `ctrl a` to `ctrl z`, i found it is `1` to `26`, so i create this pr.

thanks for your review my pr.

thanks


image

**Comment by chyroc** [comment]
@tj can you take some minutes to review my pr, thanks.

**Comment by tj** [comment]
ahh yea the "control characters" already have [names & constants](https://github.com/tj/go-terminput/blob/master/keyboard.go#L21-L51), so I'm not sure about adding more.

We could detect if those are pressed and add `ModCtrl` and populate the rune so `Rune()` returns what you'd expect, as well as `Ctrl()`, if that makes sense.

If you run `man ascii` in the terminal you should see the list, we should be able to just add 140 to the control character's numeric value to get the lowercase letter character

**Comment by chyroc** [comment]
hi, i click `ctrl a`, but ,`.Ctrl()` is not true, so i do this pr, to fix this

**Pull request closed without merging**
